TEST: whitespace cleanup

diff --git a/test/r5p/device/rv64i_m/Makefile.include b/test/r5p/device/rv64i_m/Makefile.include
--- a/test/r5p/device/rv64i_m/Makefile.include
+++ b/test/r5p/device/rv64i_m/Makefile.include
@@ -15,23 +15,24 @@ COMPILE_CMD=\
 	$$(RISCV_OBJCOPY) -j .data -O binary $$@ $$@_ls.bin; \
 	$$(RISCV_OBJCOPY)          -O binary $$@ $$@.bin
 
-OBJ_CMD = $$(RISCV_OBJDUMP) $$@ -D > $$@.objdump; \
-	  $$(RISCV_OBJDUMP) $$@ --source > $$@.debug; \
-	  $$(RISCV_READELF) -a $$@ > $$@.readelf
+OBJ_CMD=\
+	$$(RISCV_OBJDUMP) $$@ -D > $$@.objdump; \
+	$$(RISCV_OBJDUMP) $$@ --source > $$@.debug; \
+	$$(RISCV_READELF) -a $$@ > $$@.readelf
 
 COMPILE_TARGET=\
-	    $(COMPILE_CMD); \
-        if [ $$$$? -ne 0 ] ; \
-            then \
-            echo "\e[31m$$(RISCV_GCC) failed for target $$(@) \e[39m" ; \
-            exit 1 ; \
-        fi ; \
-	    $(OBJ_CMD); \
-        if [ $$$$? -ne 0 ] ; \
-            then \
-            echo "\e[31m $$(RISCV_OBJDUMP) failed for target $$(@) \e[39m" ; \
-            exit 1 ; \
-        fi ;
+	$(COMPILE_CMD); \
+	if [ $$$$? -ne 0 ] ; \
+		then \
+		echo "\e[31m$$(RISCV_GCC) failed for target $$(@) \e[39m" ; \
+		exit 1 ; \
+	fi ; \
+	$(OBJ_CMD); \
+	if [ $$$$? -ne 0 ] ; \
+		then \
+		echo "\e[31m $$(RISCV_OBJDUMP) failed for target $$(@) \e[39m" ; \
+		exit 1 ; \
+	fi ;
 
 RUN_TARGET=\
 	make -C $(TARGETDIR)/../sim/verilator -f Makefile XLEN=64 \
